version: 0.2

env:
  variables:
    VITE_API_BASE_URL: ""

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export NODE_ENV=development
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'