version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - npm install typescript --save-dev
  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'